# Generated by Django 4.0.1 on 2022-05-24 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categorie_remove_item_todolist_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('desc', models.CharField(blank=True, max_length=700, null=True)),
                ('sku', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='product_images')),
                ('cat', models.CharField(blank=True, max_length=20, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
