# Generated by Django 4.0.1 on 2022-05-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='earning',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.IntegerField(blank=True, default=0, max_length=400, null=True),
        ),
    ]
