# Generated by Django 4.0.1 on 2022-05-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='actual_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
